export const lyrics = [
  { text: "", textDelay: 6000 },
  { text: "You know,", textDelay: 2000 },
  { text: "You know,", textDelay: 1000 },
  { text: "where you are with", textDelay: 3800 },
  { text: "You know,", textDelay: 900 },
  { text: "where you are with", textDelay: 3000 },
  { text: "floor collapsing,", textDelay: 3000 },
  { text: "floating,", textDelay: 3000 },
  { text: "bouncing back and", textDelay: 2000 },
  { text: "one", textDelay: 1000 },
  { text: "day", textDelay: 1000 },
  { text: "I am gonna", textDelay: 2000 },
  { text: "grow wings.", textDelay: 3000 },
  { text: "A chemical reaction", textDelay: 3000 },
  { text: "Hysterical", textDelay: 2000},
  { text: "and useless", textDelay: 3000 },
  { text: "Hysterical and", textDelay: 3000 },
  { text: "Let down", textDelay: 1000 },
  { text: "and hanging around", textDelay: 7000 },
  { text: "Crushed like a bug", textDelay: 2000 },
  { text: "in the ground", textDelay: 4000 },
  { text: "Let down and hanging around.", textDelay: 2000 },
];
