export const lyrics = [
  { text: "", textDelay: 6000 },
  { text: "You know,", textDelay: 2000 },
  { text: "You know,", textDelay: 1000 },
  { text: "where you are with", textDelay: 3800 },
  { text: "You know,", textDelay: 900 },
  { text: "where you are with", textDelay: 2900 },
  { text: "floor collapsing,", textDelay: 2000 },
  { text: "floating,", textDelay: 3000 },
  { text: "bouncing back and", textDelay: 2100 },
  { text: "one", textDelay: 1100 },
  { text: "day", textDelay: 2000 },
  { text: "(I am gonna", textDelay: 1000 },
  { text: "grow wings).", textDelay: 4000 },
  { text: "You know, where you are", textDelay: 5000 },
  { text: "You know, where you are", textDelay: 4000},
  { text: "You know, where you are", textDelay: 2000 },
  { text: "Let down", textDelay: 1000 },
  { text: "and hanging around", textDelay: 5000 },
  { text: "Crushed like a bug", textDelay: 3000 },
  { text: "in the ground", textDelay: 4000 },
  { text: "Let down and hanging around.", textDelay: 2000 },
];
